### ISSUE TITLE
Could you give me your codes of npu tools?

### ISSUE THREAD

**Issue by xtanitfy** [cchaiyatad/intern2020#1]
I can't find the convert_caffe.py or convert_onnx.py in my code. If you can give me the code,I'm very thanks for you!!!

**Comment by cchaiyatad** [comment]
If you mean convert_caffe.py and convert_onnx.py in [NPU SDK](https://docs.khadas.com/vim3/HowToUseNpu.html/). I also don't have them. They don't give source code of the converter code. I think you have to contact them in Khadas forum

**Comment by xtanitfy** [comment]
@cchaiyatad OK,thanks!
